package:
    name: fastqc_parser
    version: 1.0.1beta

source:
    git_rev: v1.0.1beta
    git_url: https://github.com/jfear/fastqc_parser.git

build:
    number: 0
    skip: False

requirements:
    run:
        - biopython >=1.66
        - numpy >=1.10.4
        - pandas >=0.17.1
        - PyYAML >=3.11

test:

about:
    home: https://github.com/jfear/fastqc_parser.git
    license: MIT
