package:
    name: fastqc_parser
    version: 1.0.1beta

source:
    git_rev: v1.0.1beta
    git_url: https://github.com/jfear/fastqc_parser.git

build:
    number: 0
    skip: False

requirements:
    build:
        - python
        - setuptools
        - pyyaml
        - biopython 
        - numpy
        - pandas
    run:
        - python 
        - biopython 
        - numpy
        - pandas
        - pyyaml
test:
    requires:
        - pyyaml

about:
    home: https://github.com/jfear/fastqc_parser.git
    license: MIT
